// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stigsmith.Api.Persistence;

#nullable disable

namespace Stigsmith.Api.Persistence.Migrations
{
    [DbContext(typeof(StigsmithDbContext))]
    [Migration("20260914233923_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stigsmith.Api.Persistence.ChecklistRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostFqdn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostMac")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWebOrDatabase")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StigId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StigReleaseInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StigTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StigVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebDbInstance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebDbSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostName");

                    b.HasIndex("ImportedAt");

                    b.ToTable("checklists", (string)null);
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.FindingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Automatability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CciRefs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassificationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discussion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FindingDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FixText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHighRisk")
                        .HasColumnType("boolean");

                    b.Property<string>("NumericId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskCategories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumericId");

                    b.HasIndex("ChecklistId", "Automatability");

                    b.HasIndex("ChecklistId", "RuleId")
                        .IsUnique();

                    b.HasIndex("ChecklistId", "Status");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.GenerationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PromptSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RetrievedExampleIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetOs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yaml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FindingId", "CreatedAt");

                    b.ToTable("generations", (string)null);
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.ValidationRunRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplyOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContainerImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FailedStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid");

                    b.Property<int>("IdempotencyChangedCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LintOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepairAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("ScanStatusAfter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanStatusBefore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SyntaxCheckOutput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "StartedAt");

                    b.ToTable("validation_runs", (string)null);
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.FindingRecord", b =>
                {
                    b.HasOne("Stigsmith.Api.Persistence.ChecklistRecord", "Checklist")
                        .WithMany("Findings")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.GenerationRecord", b =>
                {
                    b.HasOne("Stigsmith.Api.Persistence.FindingRecord", "Finding")
                        .WithMany("Generations")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.ValidationRunRecord", b =>
                {
                    b.HasOne("Stigsmith.Api.Persistence.GenerationRecord", "Generation")
                        .WithMany("ValidationRuns")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.ChecklistRecord", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.FindingRecord", b =>
                {
                    b.Navigation("Generations");
                });

            modelBuilder.Entity("Stigsmith.Api.Persistence.GenerationRecord", b =>
                {
                    b.Navigation("ValidationRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
