<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Stigsmith.Checklists\Stigsmith.Checklists.csproj" />
    <ProjectReference Include="..\Stigsmith.Rules\Stigsmith.Rules.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
