using System.Text;

namespace Stigsmith.Validation;

/// <summary>
/// Wraps generated tasks into a playbook that can actually be run.
/// </summary>
/// <remarks>
/// The model is asked for tasks, not a play, so something has to supply the play header. Doing it here rather
/// than asking the model for it means the header is identical every time and cannot drift — and it keeps
/// <c>hosts:</c> out of the model's output entirely, which is both one less thing to get wrong and one less
/// place a hostname could appear.
/// </remarks>
public static class PlaybookBuilder
{
    /// <summary>
    /// Builds a playbook targeting the container itself. <c>hosts: localhost</c> with a local connection: the
    /// sandbox <em>is</em> the target, so there is no inventory and no host to name.
    /// </summary>
    public static string Build(string tasksYaml, string? ruleVersion = null)
    {
        var body = new StringBuilder();
        body.AppendLine("---");
        body.AppendLine("# Generated by Stigsmith for validation in a disposable container.");
        if (ruleVersion is { Length: > 0 }) body.AppendLine($"# Rule: {ruleVersion}");
        body.AppendLine("- name: Stigsmith validation play");
        body.AppendLine("  hosts: localhost");
        body.AppendLine("  connection: local");
        body.AppendLine("  become: true");
        // Facts are not needed and gathering them in a minimal container is slow and can fail outright.
        body.AppendLine("  gather_facts: false");
        body.AppendLine("  tasks:");
        body.Append(Indent(tasksYaml, "    "));
        if (!tasksYaml.EndsWith('\n')) body.AppendLine();

        return body.ToString();
    }

    /// <summary>
    /// Variable defaults for the play, so a task referencing a house variable does not fail as undefined.
    /// </summary>
    /// <remarks>
    /// Generated tasks are asked to match the operator's conventions, which means they reference variables from
    /// the operator's role — including the per-rule toggle. In validation there is no role to supply them, so
    /// undefined-variable failures would be attributed to the generated Ansible when the real cause is a missing
    /// defaults file. Every referenced variable gets a value, and the toggles get <c>true</c> so the task runs.
    /// </remarks>
    public static string BuildVarsFile(IEnumerable<string> variableNames, IDictionary<string, string>? known = null)
    {
        var body = new StringBuilder();
        body.AppendLine("---");
        foreach (var name in variableNames.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
        {
            if (known is not null && known.TryGetValue(name, out var value))
                body.AppendLine($"{name}: {value}");
            else
                body.AppendLine($"{name}: true");
        }
        return body.ToString();
    }

    private static string Indent(string text, string prefix) =>
        string.Join('\n', text.ReplaceLineEndings("\n").Split('\n')
            .Select(l => l.Length == 0 ? l : prefix + l));
}
