using System.Text;

namespace Stigsmith.Validation;

/// <summary>
/// Wraps generated tasks into a playbook that can actually be run.
/// </summary>
/// <remarks>
/// The model is asked for tasks, not a play, so something has to supply the play header. Doing it here rather
/// than asking the model for it means the header is identical every time and cannot drift — and it keeps
/// <c>hosts:</c> out of the model's output entirely, which is both one less thing to get wrong and one less
/// place a hostname could appear.
/// </remarks>
public static class PlaybookBuilder
{
    /// <summary>
    /// Builds a playbook targeting the container itself. <c>hosts: localhost</c> with a local connection: the
    /// sandbox <em>is</em> the target, so there is no inventory and no host to name.
    /// </summary>
    public static string Build(string tasksYaml, string? ruleVersion = null, IReadOnlyList<string>? handlerNames = null)
    {
        var body = new StringBuilder();
        body.AppendLine("---");
        body.AppendLine("# Generated by Stigsmith for validation in a disposable container.");
        if (ruleVersion is { Length: > 0 }) body.AppendLine($"# Rule: {ruleVersion}");
        body.AppendLine("- name: Stigsmith validation play");
        body.AppendLine("  hosts: localhost");
        body.AppendLine("  connection: local");
        body.AppendLine("  become: true");
        // Facts are not needed and gathering them in a minimal container is slow and can fail outright.
        body.AppendLine("  gather_facts: false");
        body.AppendLine("  tasks:");
        body.Append(Indent(tasksYaml, "    "));
        if (!tasksYaml.EndsWith('\n')) body.AppendLine();

        // The role's handlers, stubbed by name, so `notify` resolves. A restart or reload is not what the sandbox
        // proves; the stub says so in its output rather than pretending.
        if (handlerNames is { Count: > 0 })
        {
            body.AppendLine("  handlers:");
            foreach (var name in handlerNames)
            {
                body.AppendLine($"    - name: \"{name.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"");
                body.AppendLine("      ansible.builtin.debug:");
                body.AppendLine("        msg: Handler stubbed in the Stigsmith validation sandbox.");
            }
        }

        return body.ToString();
    }

    /// <summary>
    /// Variable defaults for the play, so a task referencing a house variable does not fail as undefined.
    /// </summary>
    /// <remarks>
    /// Generated tasks are asked to match the operator's conventions, which means they reference variables from
    /// the operator's role — including the per-rule toggle. In validation there is no role to supply them, so
    /// undefined-variable failures would be attributed to the generated Ansible when the real cause is a missing
    /// defaults file. Every referenced variable gets a value, and the toggles get <c>true</c> so the task runs.
    /// </remarks>
    public static string BuildVarsFile(IEnumerable<string> variableNames, IDictionary<string, string>? known = null)
    {
        var names = variableNames.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        // An empty document is not a mapping, and `-e @vars.yml` on one makes ansible-playbook print its usage and
        // exit before reading the playbook — which looked like a syntax failure of every rule with no variables.
        if (names.Length == 0) return "--- {}\n";

        var body = new StringBuilder();
        body.AppendLine("---");
        foreach (var name in names)
        {
            if (known is not null && known.TryGetValue(name, out var value))
                body.AppendLine($"{name}: {value}");
            else
                body.AppendLine($"{name}: true");
        }
        return body.ToString();
    }

    private static string Indent(string text, string prefix) =>
        string.Join('\n', text.ReplaceLineEndings("\n").Split('\n')
            .Select(l => l.Length == 0 ? l : prefix + l));
}
