<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Stigsmith.Checklists\Stigsmith.Checklists.csproj" />
    <ProjectReference Include="..\Stigsmith.Generation\Stigsmith.Generation.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
