"""Synthetic RHEL 8 STIG rule catalog.

Rule text here is authored in DISA's idiom from the public STIG structure; it is not copied from a
proprietary source and it describes no real system. Hosts and addresses in the generated fixtures are
synthetic by construction (see make_fixtures.py) -- see constraint 2 in the README.

Each entry: (vuln, version, severity, title, discussion, check, fix, expected_class, risk_tags)
`expected_class` and `risk_tags` are the answers the M3 classifier is graded against; they are not
written into the fixtures themselves, only into the expectations file.
"""

A, M, N = "automatable", "manual", "needs-review"

CATALOG = [
    ("V-230221", "RHEL-08-010000", "high",
     "RHEL 8 must be a vendor-supported release.",
     "An operating system release is considered supported if the vendor continues to provide security patches.",
     "Verify the version of the operating system is vendor supported.\n\nCheck the version with the following command:\n\n$ cat /etc/redhat-release\n\nIf the release is not supported by the vendor, this is a finding.",
     "Upgrade to a supported version of RHEL 8.",
     N, []),

    ("V-230222", "RHEL-08-010010", "medium",
     "RHEL 8 vendor packaged system security patches and updates must be installed and up to date.",
     "Timely patching is critical for maintaining the operational availability and integrity of a system.",
     "Verify the operating system security patches are up to date with the following command:\n\n$ sudo yum history list | more\n\nIf the system is not being patched per the organizational patch schedule, this is a finding.",
     "Install the operating system patches or updated packages available from the vendor.",
     N, []),

    ("V-230223", "RHEL-08-010020", "high",
     "RHEL 8 must implement NIST FIPS-validated cryptography for the following: to provision digital signatures, to generate cryptographic hashes, and to protect data.",
     "Use of weak or untested encryption algorithms undermines the purposes of using encryption to protect data.",
     "Verify the operating system implements FIPS mode with the following command:\n\n$ sudo fips-mode-setup --check\nFIPS mode is enabled.\n\nIf FIPS mode is not enabled, this is a finding.",
     "Configure the operating system to implement FIPS mode with the following command:\n\n$ sudo fips-mode-setup --enable\n\nReboot the system for the change to take effect.",
     A, ["crypto"]),

    ("V-230224", "RHEL-08-010030", "medium",
     "All RHEL 8 local disk partitions must implement cryptographic mechanisms to prevent unauthorized disclosure or modification of all information that requires at rest protection.",
     "Operating systems handling data requiring data at rest protections must employ cryptographic mechanisms to prevent unauthorized disclosure and modification of the information at rest.",
     "Verify RHEL 8 prevents unauthorized disclosure or modification of all information requiring at rest protection by using disk encryption.\n\nIf there is a documented and approved reason for not having data-at-rest encryption, this requirement is Not Applicable.\n\nDetermine the partition layout with the following command:\n\n$ sudo blkid\n\nIf partitions containing information requiring at rest protection are not encrypted, this is a finding.",
     "Configure RHEL 8 to prevent unauthorized modification of all information at rest by using disk encryption.\n\nEncrypting a partition in an already installed system is more difficult, because existing partitions will need to be resized and changed. To encrypt an entire partition, dedicate a partition for encryption in the partition layout.",
     N, []),

    ("V-230225", "RHEL-08-010040", "medium",
     "RHEL 8 must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a ssh logon.",
     "Display of a standardized and approved use notification before granting access to the operating system ensures privacy and security notification verbiage used is consistent with applicable federal laws.",
     "Verify any publicly accessible connection to the operating system displays the Standard Mandatory DoD Notice and Consent Banner before granting access.\n\nCheck for the location of the banner file being used with the following command:\n\n$ sudo grep -ir banner /etc/ssh/sshd_config\nbanner /etc/issue\n\nIf the line is commented out or missing, this is a finding.",
     "Configure RHEL 8 to display the Standard Mandatory DoD Notice and Consent Banner before granting access to the system via SSH.\n\nEdit the \"/etc/ssh/sshd_config\" file to uncomment the banner keyword and configure it to point to a file that will contain the logon banner:\n\nBanner /etc/issue\n\nThe SSH service must be restarted for changes to take effect.",
     A, ["sshd"]),

    ("V-230227", "RHEL-08-010060", "medium",
     "RHEL 8 must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a graphical user logon.",
     "The banner must be acknowledged by the user prior to allowing the user access to the operating system.",
     "Verify RHEL 8 displays the Standard Mandatory DoD Notice and Consent Banner before granting access to the operating system via a graphical user logon.\n\nNote: This requirement assumes the use of the RHEL 8 default graphical user interface, Gnome Shell. If the system does not have any graphical user interface installed, this requirement is Not Applicable.\n\nCheck that the operating system displays the exact Standard Mandatory DoD Notice and Consent Banner text with the command:\n\n$ sudo grep banner-message-text /etc/dconf/db/local.d/*\n\nIf the banner does not match the Standard Mandatory DoD Notice and Consent Banner exactly, this is a finding.",
     "Configure the operating system to display the Standard Mandatory DoD Notice and Consent Banner before granting access to the system.\n\nCreate a database to contain the system-wide graphical user logon settings (if it does not already exist) with the following command:\n\n$ sudo touch /etc/dconf/db/local.d/01-banner-message\n\nAdd the following line to the [org/gnome/login-screen] section:\n\nbanner-message-enable=true\n\nRun the following command to update the database:\n\n$ sudo dconf update",
     A, []),

    ("V-230229", "RHEL-08-010090", "medium",
     "RHEL 8 must have the packages required for multifactor authentication installed.",
     "Using an authentication device, such as a CAC or token that is separate from the information system, ensures that even if the information system is compromised, that compromise will not affect credentials stored on the authentication device.",
     "Verify the operating system has the packages required for multifactor authentication installed with the following command:\n\n$ sudo yum list installed openssl-pkcs11\n\nIf the \"openssl-pkcs11\" package is not installed, this is a finding.",
     "Configure the operating system to implement multifactor authentication by installing the required package with the following command:\n\n$ sudo yum install openssl-pkcs11",
     A, ["authentication"]),

    ("V-230230", "RHEL-08-010100", "medium",
     "RHEL 8, for PKI-based authentication, must validate certificates by constructing a certification path (which includes status information) to an accepted trust anchor.",
     "Without path validation, an informed trust decision by the relying party cannot be made when presented with any certificate not already explicitly trusted.",
     "Verify RHEL 8 for PKI-based authentication has valid certificates by constructing a certification path to an accepted trust anchor.\n\nCheck that the system has a valid DoD root CA installed with the following command:\n\n$ sudo openssl x509 -text -in /etc/sssd/pki/sssd_auth_ca_db.pem\n\nIf the root ca file is not a DoD-approved trust anchor, this is a finding.",
     "Configure RHEL 8, for PKI-based authentication, to validate certificates by constructing a certification path to an accepted trust anchor.\n\nObtain the DoD-approved certificate bundle and install it in \"/etc/sssd/pki/sssd_auth_ca_db.pem\".",
     N, ["authentication"]),

    ("V-230231", "RHEL-08-010110", "medium",
     "RHEL 8 must encrypt all stored passwords with a FIPS 140-2 approved cryptographic hashing algorithm.",
     "Passwords need to be protected at all times, and encryption is the standard method for protecting passwords.",
     "Confirm that the interactive user account passwords are using a strong password hash with the following command:\n\n$ sudo grep -i crypt_style /etc/libuser.conf\ncrypt_style = sha512\n\nIf the \"crypt_style\" variable is not set to \"sha512\", is commented out, or does not exist, this is a finding.",
     "Configure RHEL 8 to encrypt all stored passwords with a strong cryptographic hash.\n\nEdit/modify the following line in the \"/etc/libuser.conf\" file in the [defaults] section and set \"crypt_style\" to \"sha512\":\n\ncrypt_style = sha512",
     A, ["authentication"]),

    ("V-230232", "RHEL-08-010120", "medium",
     "RHEL 8 must employ FIPS 140-2 approved cryptographic hashing algorithms for all stored passwords.",
     "The system must use a strong hashing algorithm to store the password.",
     "Verify that the shadow password suite configuration is set to encrypt password with a FIPS 140-2 approved cryptographic hashing algorithm.\n\nCheck the hashes of interactive user passwords with the following command:\n\n$ sudo cut -d: -f2 /etc/shadow\n$6$kcOnRq/5$NUEYPuyL.wghQwWssXRcLRFiiru7f5JPV6GaJhNC2aK5F3PZpE/BCCtwrxRc/AInKMNX3CdMw11m9STiql12f/\n\nIf any interactive user password hash does not begin with \"$6\", this is a finding.",
     "Lock all interactive user accounts not using SHA-512 hashing until the passwords can be regenerated with SHA-512.",
     N, ["authentication"]),

    ("V-230234", "RHEL-08-010140", "high",
     "RHEL 8 operating systems booted with United Extensible Firmware Interface (UEFI) must require authentication upon booting into single-user mode and maintenance.",
     "If the system does not require valid authentication before it boots into single-user or maintenance mode, anyone who invokes single-user or maintenance mode is granted privileged access to all files on the system.",
     "For systems that use BIOS, this is Not Applicable.\n\nVerify that an encrypted root password is set with the following command:\n\n$ sudo grep -iw grub2_password /boot/efi/EFI/redhat/user.cfg\nGRUB2_PASSWORD=grub.pbkdf2.sha512.10000.C40F1BC6...\n\nIf the root password does not begin with \"grub.pbkdf2.sha512\", this is a finding.",
     "Configure the system to encrypt the boot password for root.\n\nGenerate an encrypted grub2 password for root with the following command:\n\n$ sudo grub2-setpassword\nEnter password:\nConfirm password:",
     N, ["boot", "authentication"]),

    ("V-230237", "RHEL-08-010160", "medium",
     "The RHEL 8 pam_unix.so module must be configured in the password-auth file to use a FIPS 140-2 approved cryptographic hashing algorithm for system authentication.",
     "Unapproved mechanisms that are used for authentication to the cryptographic module are not verified and therefore cannot be relied upon to provide confidentiality or integrity.",
     "Verify that pam_unix.so module is configured to use sha512 with the following command:\n\n$ sudo grep password /etc/pam.d/password-auth | grep pam_unix\npassword sufficient pam_unix.so sha512 shadow try_first_pass use_authtok\n\nIf \"sha512\" is missing, or is commented out, this is a finding.",
     "Configure RHEL 8 to use a FIPS 140-2 approved cryptographic hashing algorithm for system authentication.\n\nEdit/modify the following line in the \"/etc/pam.d/password-auth\" file to include the sha512 option for pam_unix.so:\n\npassword sufficient pam_unix.so sha512 shadow try_first_pass use_authtok",
     A, ["pam", "authentication"]),

    ("V-230240", "RHEL-08-010171", "medium",
     "RHEL 8 must have the policycoreutils package installed.",
     "Policycoreutils contains the policy core utilities that are required for basic operation of an SELinux-enabled system.",
     "Verify the operating system has the policycoreutils package installed with the following command:\n\n$ sudo yum list installed policycoreutils\npolicycoreutils.x86_64       2.9-9.el8       @anaconda\n\nIf the policycoreutils package is not installed, this is a finding.",
     "Configure the operating system to have the policycoreutils package installed with the following command:\n\n$ sudo yum install policycoreutils",
     A, ["selinux"]),

    ("V-230244", "RHEL-08-010200", "medium",
     "RHEL 8 must be configured so that all network connections associated with SSH traffic are terminated after a period of inactivity.",
     "Terminating an idle SSH session within a short time period reduces the window of opportunity for unauthorized personnel to take control of a management session.",
     "Verify that all network connections associated with SSH traffic automatically terminate after a period of inactivity with the following command:\n\n$ sudo grep -i clientalivecountmax /etc/ssh/sshd_config\nClientAliveCountMax 1\n\nIf \"ClientAliveCountMax\" does not exist, is not set to a value of \"1\", or is commented out, this is a finding.",
     "Configure RHEL 8 so that all network connections associated with SSH traffic terminate after a period of inactivity.\n\nAdd the following line to the \"/etc/ssh/sshd_config\" file:\n\nClientAliveCountMax 1\n\nThe SSH service must be restarted for changes to take effect.",
     A, ["sshd"]),

    ("V-230251", "RHEL-08-010290", "medium",
     "The RHEL 8 SSH server must be configured to use only Message Authentication Codes (MACs) employing FIPS 140-2 validated cryptographic hash algorithms.",
     "Without cryptographic integrity protections, information can be altered by unauthorized users without detection.",
     "Verify the SSH server is configured to use only MACs employing FIPS 140-2-approved algorithms with the following command:\n\n$ sudo grep -i macs /etc/crypto-policies/back-ends/openssh.config\nMACs hmac-sha2-512,hmac-sha2-256\n\nIf the MACs entries in the \"openssh.config\" file have any hashes other than \"hmac-sha2-512\" and \"hmac-sha2-256\", the order differs from the example above, or they are missing or commented out, this is a finding.",
     "Configure the RHEL 8 SSH server to use only MACs employing FIPS 140-2-approved algorithms.\n\nUpdate the \"/etc/crypto-policies/back-ends/openssh.config\" file to include these MACs employing FIPS 140-2-approved algorithms:\n\nMACs hmac-sha2-512,hmac-sha2-256\n\nA reboot is required for the changes to take effect.",
     A, ["sshd", "crypto"]),

    ("V-230257", "RHEL-08-010300", "medium",
     "RHEL 8 system commands must have mode 755 or less permissive.",
     "If RHEL 8 were to allow any user to make changes to software libraries, then those changes might be implemented without undergoing the appropriate testing and approvals.",
     "Verify the system commands contained in the following directories have mode 755 or less permissive with the following command:\n\n$ sudo find -L /bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin -perm /022 -type f -exec ls -l {} \\;\n\nIf any system commands are found to be group-writable or world-writable, this is a finding.",
     "Configure the system commands to be protected from unauthorized access.\n\nRun the following command, replacing \"[FILE]\" with any system command with a mode more permissive than 755:\n\n$ sudo chmod 755 [FILE]",
     A, ["filesystem"]),

    ("V-230262", "RHEL-08-010330", "medium",
     "RHEL 8 library files must have mode 755 or less permissive.",
     "If RHEL 8 were to allow any user to make changes to software libraries, then those changes might be implemented without undergoing the appropriate testing and approvals.",
     "Verify the system-wide shared library files contained in the following directories have mode 755 or less permissive with the following command:\n\n$ sudo find -L /lib /lib64 /usr/lib /usr/lib64 -perm /022 -type f -exec ls -l {} \\;\n\nIf any system-wide shared library file is found to be group-writable or world-writable, this is a finding.",
     "Configure the library files to be protected from unauthorized access. Run the following command, replacing \"[FILE]\" with any library file with a mode more permissive than 755:\n\n$ sudo chmod 755 [FILE]",
     A, ["filesystem"]),

    ("V-230265", "RHEL-08-010359", "medium",
     "The RHEL 8 file integrity tool must be configured to verify Access Control Lists (ACLs).",
     "ACLs can provide permissions beyond those permitted through the file mode and must be verified by the file integrity tools.",
     "Verify the file integrity tool is configured to verify ACLs.\n\nIf AIDE is not installed, ask the System Administrator how file integrity checks are performed on the system.\n\nIf there is no application installed to perform file integrity checks, this is a finding.\n\nNote: AIDE is highly configurable at install time. This requirement assumes the \"aide.conf\" file is under the \"/etc\" directory.\n\nUse the following command to determine if the file is in another location:\n\n$ sudo find / -name aide.conf\n\nCheck the \"aide.conf\" file to determine if the \"acl\" rule has been added to the rule list being applied to the files and directories selection lists.\n\nIf the \"acl\" rule is not being used on all selection lines in the \"/etc/aide.conf\" file, is commented out, or ACLs are not being checked by another file integrity tool, this is a finding.",
     "Configure the file integrity tool to check file and directory ACLs.\n\nIf AIDE is installed, ensure the \"acl\" rule is present on all uncommented file and directory selection lists.",
     N, []),

    ("V-230269", "RHEL-08-010370", "high",
     "RHEL 8 must prevent the installation of software, patches, service packs, device drivers, or operating system components from a repository without verification they have been digitally signed using a certificate that is issued by a Certificate Authority (CA) that is recognized and approved by the organization.",
     "Changes to any software components can have significant effects on the overall security of the operating system.",
     "Verify the operating system prevents the installation of patches, service packs, device drivers, or operating system components from a repository without verification that they have been digitally signed using a certificate that is recognized and approved by the organization.\n\nCheck that yum verifies the signature of packages from a repository prior to install with the following command:\n\n$ sudo grep gpgcheck /etc/dnf/dnf.conf\ngpgcheck=1\n\nIf \"gpgcheck\" is not set to \"1\", or is missing, this is a finding.",
     "Configure the operating system to verify the signature of packages from a repository prior to install by setting the following option in the \"/etc/dnf/dnf.conf\" file:\n\ngpgcheck=1",
     A, ["packages"]),

    ("V-230270", "RHEL-08-010371", "high",
     "RHEL 8 must prevent the loading of a new kernel for later execution.",
     "Changes to any software components can have significant effects on the overall security of the operating system.",
     "Verify the operating system is configured to disable kernel image loading.\n\nCheck the status of the kernel.kexec_load_disabled kernel parameter with the following command:\n\n$ sudo sysctl kernel.kexec_load_disabled\nkernel.kexec_load_disabled = 1\n\nIf \"kernel.kexec_load_disabled\" is not set to \"1\" or is missing, this is a finding.",
     "Configure the operating system to disable kernel image loading.\n\nAdd or edit the following line in a system configuration file in the \"/etc/sysctl.d/\" directory:\n\nkernel.kexec_load_disabled = 1\n\nLoad settings from all system configuration files with the following command:\n\n$ sudo sysctl --system",
     A, ["kernel"]),

    ("V-230271", "RHEL-08-010372", "medium",
     "RHEL 8 must enable kernel parameters to enforce discretionary access control on symlinks.",
     "By enabling the fs.protected_symlinks kernel parameter, symbolic links are permitted to be followed only when outside a sticky world-writable directory.",
     "Verify the operating system is configured to enable DAC on symlinks with the following command:\n\n$ sudo sysctl fs.protected_symlinks\nfs.protected_symlinks = 1\n\nIf \"fs.protected_symlinks\" is not set to \"1\" or is missing, this is a finding.",
     "Configure the operating system to enable DAC on symlinks with the following command:\n\nAdd or edit the following line in a system configuration file in the \"/etc/sysctl.d/\" directory:\n\nfs.protected_symlinks = 1\n\nLoad settings from all system configuration files with the following command:\n\n$ sudo sysctl --system",
     A, ["kernel"]),

    ("V-230280", "RHEL-08-010440", "medium",
     "YUM must remove all software components after updated versions have been installed on RHEL 8.",
     "Previous versions of software components that are not removed from the information system after updates have been installed may be exploited by adversaries.",
     "Verify the operating system removes all software components after updated versions have been installed.\n\nCheck if yum is configured to remove unneeded packages with the following command:\n\n$ sudo grep -i clean_requirements_on_remove /etc/dnf/dnf.conf\nclean_requirements_on_remove=True\n\nIf \"clean_requirements_on_remove\" is not set to \"True\", \"1\", or \"yes\", or is commented out, this is a finding.",
     "Configure the operating system to remove all software components after updated versions have been installed.\n\nSet the \"clean_requirements_on_remove\" option to \"True\" in the \"/etc/dnf/dnf.conf\" file:\n\nclean_requirements_on_remove=True",
     A, ["packages"]),

    ("V-230283", "RHEL-08-010460", "medium",
     "There must be no shosts.equiv files on the RHEL 8 operating system.",
     "The shosts.equiv files are used to configure host-based authentication for the system via SSH. Host-based authentication is not sufficient for preventing unauthorized access to the system.",
     "Verify there are no \"shosts.equiv\" files on RHEL 8 with the following command:\n\n$ sudo find / -name shosts.equiv\n\nIf a \"shosts.equiv\" file is found, this is a finding.",
     "Remove any found \"shosts.equiv\" files from the system.\n\n$ sudo rm /etc/ssh/shosts.equiv",
     A, ["sshd", "authentication"]),

    ("V-230286", "RHEL-08-010500", "high",
     "The RHEL 8 SSH daemon must perform strict mode checking of home directory configuration files.",
     "If other users have access to modify user-specific SSH configuration files, they may be able to log on to the system as another user.",
     "Verify the SSH daemon performs strict mode checking of home directory configuration files with the following command:\n\n$ sudo grep -i strictmodes /etc/ssh/sshd_config\nStrictModes yes\n\nIf \"StrictModes\" is set to \"no\", is missing, or the returned line is commented out, this is a finding.",
     "Configure the SSH daemon to perform strict mode checking of home directory configuration files.\n\nUncomment the \"StrictModes\" keyword in \"/etc/ssh/sshd_config\" and set the value to \"yes\":\n\nStrictModes yes\n\nThe SSH service must be restarted for changes to take effect.",
     A, ["sshd"]),

    ("V-230296", "RHEL-08-010550", "medium",
     "RHEL 8 must not permit direct logons to the root account using remote access via SSH.",
     "Even though the communications channel may be encrypted, an additional layer of security is gained by extending the policy of not logging on directly as root.",
     "Verify remote access using SSH prevents users from logging on directly as \"root\" with the following command:\n\n$ sudo grep -i permitrootlogin /etc/ssh/sshd_config\nPermitRootLogin no\n\nIf the \"PermitRootLogin\" keyword is set to any value other than \"no\", is missing, or is commented out, this is a finding.",
     "Configure RHEL 8 to stop users from logging on remotely as the \"root\" user via SSH.\n\nEdit the appropriate \"/etc/ssh/sshd_config\" file to uncomment or add the line for the \"PermitRootLogin\" keyword and set its value to \"no\":\n\nPermitRootLogin no\n\nThe SSH service must be restarted for changes to take effect.",
     A, ["sshd", "authentication"]),

    ("V-230301", "RHEL-08-010561", "medium",
     "The rsyslog service must be running in RHEL 8.",
     "Configuring RHEL 8 to implement organization-wide security implementation guides and security checklists ensures compliance with federal standards.",
     "Verify that \"rsyslog\" is being used to monitor auditing on the system.\n\nCheck that the \"rsyslog\" service is enabled and active with the following commands:\n\n$ sudo systemctl is-enabled rsyslog\nenabled\n\n$ sudo systemctl is-active rsyslog\nactive\n\nIf the service is not enabled and active, this is a finding.",
     "Start the \"rsyslog\" service and enable it to start at boot with the following commands:\n\n$ sudo systemctl enable --now rsyslog",
     A, ["services"]),

    ("V-230327", "RHEL-08-010571", "medium",
     "RHEL 8 must prevent files with the setuid and setgid bit set from being executed on the /boot directory.",
     "The \"nosuid\" mount option causes the system not to execute \"setuid\" and \"setgid\" files with owner privileges.",
     "Verify the /boot directory is mounted with the \"nosuid\" option with the following command:\n\n$ sudo mount | grep '\\s/boot\\s'\n/dev/sda1 on /boot type xfs (rw,nosuid,relatime,seclabel,attr2,inode64,noquota)\n\nIf the /boot file system does not have the \"nosuid\" option set, this is a finding.",
     "Configure the \"/etc/fstab\" to use the \"nosuid\" option on the /boot directory.",
     N, ["filesystem"]),

    ("V-230332", "RHEL-08-020010", "medium",
     "RHEL 8 must automatically lock an account when three unsuccessful logon attempts occur.",
     "By limiting the number of failed logon attempts, the risk of unauthorized system access via user password guessing, otherwise known as brute-force attacks, is reduced.",
     "Check that the system locks an account after three unsuccessful logon attempts with the following commands:\n\n$ sudo grep 'deny =' /etc/security/faillock.conf\ndeny = 3\n\nIf the \"deny\" option is not set to \"3\" or less (but not \"0\"), is missing or commented out, this is a finding.",
     "Configure the operating system to lock an account when three unsuccessful logon attempts occur.\n\nAdd/Modify the \"/etc/security/faillock.conf\" file to match the following line:\n\ndeny = 3",
     A, ["pam", "authentication"]),

    ("V-230346", "RHEL-08-020024", "medium",
     "RHEL 8 must limit the number of concurrent sessions to ten for all accounts and/or account types.",
     "Operating system management includes the ability to control the number of users and user sessions that utilize an operating system.",
     "Verify the operating system limits the number of concurrent sessions to \"10\" for all accounts and/or account types with the following command:\n\n$ sudo grep -r maxlogins /etc/security/limits.conf /etc/security/limits.d/*.conf\n* hard maxlogins 10\n\nIf the \"maxlogins\" item is missing or the value is not set to 10 or less, this is a finding.",
     "Configure the operating system to limit the number of concurrent sessions to ten for all accounts and/or account types.\n\nAdd the following line to the top of the /etc/security/limits.conf or in a \".conf\" file defined in /etc/security/limits.d/:\n\n* hard maxlogins 10",
     A, ["authentication"]),

    ("V-230348", "RHEL-08-020030", "medium",
     "RHEL 8 must enable a user session lock until that user re-establishes access using established identification and authentication procedures for graphical user interfaces.",
     "A session lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system.",
     "Verify the operating system enables a user's session lock until that user re-establishes access using established identification and authentication procedures with the following command:\n\n$ sudo grep -i lock-enabled /etc/dconf/db/local.d/*\nlock-enabled=true\n\nIf the \"lock-enabled\" setting is missing or is not set to \"true\", this is a finding.",
     "Configure the operating system to enable a user's session lock until that user re-establishes access.\n\nAdd the setting to enable screen locking in the [org/gnome/desktop/screensaver] section of /etc/dconf/db/local.d/00-screensaver:\n\nlock-enabled=true\n\nUpdate the system databases:\n\n$ sudo dconf update",
     A, []),

    ("V-230352", "RHEL-08-020060", "medium",
     "RHEL 8 must automatically lock graphical user sessions after 15 minutes of inactivity.",
     "A session time-out lock is a temporary action taken when a user stops work and moves away from the immediate physical vicinity of the information system but does not log out.",
     "Verify the operating system initiates a session lock after a 15-minute period of inactivity for graphical user interfaces with the following command:\n\n$ sudo grep -i idle-delay /etc/dconf/db/local.d/*\nidle-delay=uint32 900\n\nIf the \"idle-delay\" setting is missing or is not set to \"900\" or less, this is a finding.",
     "Configure the operating system to initiate a session lock after a 15-minute period of inactivity for graphical user interfaces.\n\nCreate a database to contain the system-wide screensaver settings with the following command:\n\n$ sudo touch /etc/dconf/db/local.d/00-screensaver\n\nAdd the following line to the [org/gnome/desktop/session] section:\n\nidle-delay=uint32 900\n\nUpdate the system databases:\n\n$ sudo dconf update",
     A, []),

    ("V-230357", "RHEL-08-020100", "medium",
     "RHEL 8 must ensure the password complexity module is enabled in the password-auth file.",
     "Use of a complex password helps to increase the time and resources required to compromise the password.",
     "Verify the pam_pwquality.so module is present in the \"/etc/pam.d/password-auth\" file:\n\n$ sudo grep pam_pwquality /etc/pam.d/password-auth\npassword required pam_pwquality.so\n\nIf the line is commented out or missing, this is a finding.",
     "Configure RHEL 8 to enable the password complexity module in the password-auth file.\n\nAdd the following line to the \"/etc/pam.d/password-auth\" file (or modify the line to have the required value):\n\npassword required pam_pwquality.so",
     A, ["pam", "authentication"]),

    ("V-230364", "RHEL-08-020170", "medium",
     "RHEL 8 must require the change of at least four character classes when passwords are changed.",
     "Use of a complex password helps to increase the time and resources required to compromise the password.",
     "Verify the value of the \"minclass\" option in \"/etc/security/pwquality.conf\" with the following command:\n\n$ sudo grep minclass /etc/security/pwquality.conf\nminclass = 4\n\nIf the value of \"minclass\" is set to less than \"4\" or is commented out, this is a finding.",
     "Configure the operating system to require the change of at least four character classes when passwords are changed by setting the \"minclass\" option in \"/etc/security/pwquality.conf\":\n\nminclass = 4",
     A, ["authentication"]),

    ("V-230366", "RHEL-08-020190", "medium",
     "RHEL 8 must require the maximum number of repeating characters be limited to three when passwords are changed.",
     "Use of a complex password helps to increase the time and resources required to compromise the password.",
     "Check for the value of the \"maxrepeat\" option in \"/etc/security/pwquality.conf\" with the following command:\n\n$ sudo grep maxrepeat /etc/security/pwquality.conf\nmaxrepeat = 3\n\nIf the value of \"maxrepeat\" is set to more than \"3\" or is commented out, this is a finding.",
     "Configure the operating system to require the change of the number of repeating consecutive characters when passwords are changed by setting the \"maxrepeat\" option in \"/etc/security/pwquality.conf\":\n\nmaxrepeat = 3",
     A, ["authentication"]),

    ("V-230369", "RHEL-08-020220", "medium",
     "RHEL 8 passwords must have a 24 hours/1 day minimum password lifetime restriction in /etc/login.defs.",
     "Enforcing a minimum password lifetime helps to prevent repeated password changes to defeat the password reuse or history enforcement requirement.",
     "Verify the operating system enforces 24 hours/one day as the minimum password lifetime for new user accounts with the following command:\n\n$ sudo grep -i pass_min_days /etc/login.defs\nPASS_MIN_DAYS 1\n\nIf the \"PASS_MIN_DAYS\" parameter value is less than \"1\", or is commented out, this is a finding.",
     "Configure the operating system to enforce 24 hours/one day as the minimum password lifetime.\n\nAdd the following line in \"/etc/login.defs\" (or modify the line to have the required value):\n\nPASS_MIN_DAYS 1",
     A, ["authentication"]),

    ("V-230375", "RHEL-08-020250", "medium",
     "RHEL 8 must be configured in the password-auth file to prohibit password reuse for a minimum of five generations.",
     "Password complexity, or strength, is a measure of the effectiveness of a password in resisting attempts at guessing and brute-force attacks.",
     "Verify the operating system prohibits password reuse for a minimum of five generations:\n\n$ sudo grep -i remember /etc/pam.d/password-auth\npassword required pam_pwhistory.so use_authtok remember=5 retry=3\n\nIf the \"remember\" parameter value is not greater than or equal to \"5\", is commented out, or is missing, this is a finding.",
     "Configure the operating system to prohibit password reuse for a minimum of five generations.\n\nAdd the following line in \"/etc/pam.d/password-auth\":\n\npassword required pam_pwhistory.so use_authtok remember=5 retry=3",
     A, ["pam", "authentication"]),

    ("V-230380", "RHEL-08-020300", "medium",
     "RHEL 8 must enforce a minimum 15-character password length.",
     "The shorter the password, the lower the number of possible combinations that need to be tested before the password is compromised.",
     "Verify the operating system enforces a minimum 15-character password length with the following command:\n\n$ sudo grep minlen /etc/security/pwquality.conf\nminlen = 15\n\nIf the command does not return a \"minlen\" value of 15 or greater, this is a finding.",
     "Configure the operating system to enforce a minimum 15-character password length.\n\nAdd or modify the following line in \"/etc/security/pwquality.conf\":\n\nminlen = 15",
     A, ["authentication"]),

    ("V-230386", "RHEL-08-030000", "medium",
     "RHEL 8 audit records must be off-loaded onto a different system or storage media from the system being audited.",
     "Information stored in one location is vulnerable to accidental or incidental deletion or alteration.",
     "Verify the audit system off-loads audit records onto a different system or media from the system being audited with the following command:\n\n$ sudo grep -i remote_server /etc/audisp/audisp-remote.conf\nremote_server = 10.0.21.1\n\nIf a remote server is not configured, or the line is commented out, ask the System Administrator to indicate how the audit logs are off-loaded to a different system or media.\n\nIf there is no evidence that the audit logs are being off-loaded to another system or media, this is a finding.",
     "Configure the audit system to off-load audit records onto a different system or media from the system being audited.\n\nSet the remote server option in \"/etc/audisp/audisp-remote.conf\" with the IP address of the log aggregation server.",
     N, ["auditd"]),

    ("V-230387", "RHEL-08-030010", "medium",
     "RHEL 8 audit system must take appropriate action when the audit storage volume is full.",
     "It is critical that when RHEL 8 is at risk of failing to process audit logs as required, it takes action to mitigate the failure.",
     "Verify RHEL 8 takes the appropriate action when the audit storage volume is full with the following command:\n\n$ sudo grep disk_full_action /etc/audisp/audisp-remote.conf\ndisk_full_action = single\n\nIf the value of the \"disk_full_action\" option is not \"syslog\", \"single\", or \"halt\", or the line is commented out, this is a finding.",
     "Configure the audit system to take an appropriate action when the audit storage volume is full.\n\nAdd or modify the following line in \"/etc/audisp/audisp-remote.conf\":\n\ndisk_full_action = single",
     A, ["auditd"]),

    ("V-230389", "RHEL-08-030030", "medium",
     "The RHEL 8 audit log directory must be owned by root to prevent unauthorized read access.",
     "Unauthorized disclosure of audit records can reveal system and configuration data to attackers, thus compromising its confidentiality.",
     "Verify the audit log directory is owned by \"root\" with the following command:\n\n$ sudo stat -c \"%U %n\" /var/log/audit\nroot /var/log/audit\n\nIf the audit log directory is not owned by \"root\", this is a finding.",
     "Configure the audit log directory to be owned by \"root\" with the following command:\n\n$ sudo chown root /var/log/audit",
     A, ["auditd", "filesystem"]),

    ("V-230396", "RHEL-08-030063", "medium",
     "RHEL 8 must allocate an audit_backlog_limit of sufficient size to capture processes that start prior to the audit daemon.",
     "Without the capability to generate audit records, it would be difficult to establish, correlate, and investigate the events relating to an incident.",
     "Verify RHEL 8 allocates a sufficient audit_backlog_limit with the following command:\n\n$ sudo grub2-editenv list | grep audit\nkernelopts=root=/dev/mapper/rhel-root ro crashkernel=auto resume=/dev/mapper/rhel-swap rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet fips=1 audit=1 audit_backlog_limit=8192\n\nIf the \"audit_backlog_limit\" entry does not equal or exceed \"8192\", is missing, or the line is commented out, this is a finding.",
     "Configure RHEL 8 to allocate sufficient audit_backlog_limit to capture processes that start prior to the audit daemon with the following command:\n\n$ sudo grubby --update-kernel=ALL --args=audit_backlog_limit=8192\n\nAdd the argument to the default grub config so it persists across kernel updates:\n\nEdit \"/etc/default/grub\" and add \"audit_backlog_limit=8192\" to the GRUB_CMDLINE_LINUX line.",
     A, ["auditd", "boot"]),

    ("V-230423", "RHEL-08-030170", "medium",
     "Successful/unsuccessful modifications to the faillock log file in RHEL 8 must generate an audit record.",
     "Without generating audit records that are specific to the security and mission needs of the organization, it would be difficult to establish, correlate, and investigate the events relating to an incident.",
     "Verify RHEL 8 generates an audit record for all modifications to the \"/etc/sudoers\" file with the following command:\n\n$ sudo grep /etc/sudoers /etc/audit/audit.rules\n-w /etc/sudoers -p wa -k identity\n\nIf the command does not return a line, or the line is commented out, this is a finding.",
     "Configure the audit system to generate an audit event for any modification to the \"/etc/sudoers\" file.\n\nAdd or update the following rule in \"/etc/audit/rules.d/audit.rules\":\n\n-w /etc/sudoers -p wa -k identity\n\nThe audit daemon must be restarted for the changes to take effect:\n\n$ sudo augenrules --load",
     A, ["auditd"]),

    ("V-230468", "RHEL-08-030310", "medium",
     "RHEL 8 must generate audit records for any use of the \"su\" command.",
     "Reconstruction of harmful events or forensic analysis is not possible if audit records do not contain enough information.",
     "Verify RHEL 8 generates an audit record upon successful/unsuccessful attempts to use the \"su\" command with the following command:\n\n$ sudo grep -w \"/usr/bin/su\" /etc/audit/audit.rules\n-a always,exit -F path=/usr/bin/su -F perm=x -F auid>=1000 -F auid!=unset -k privileged-priv_change\n\nIf the command does not return a line, or the line is commented out, this is a finding.",
     "Configure RHEL 8 to generate an audit record upon successful/unsuccessful attempts to use the \"su\" command.\n\nAdd or update the following rule to \"/etc/audit/rules.d/audit.rules\":\n\n-a always,exit -F path=/usr/bin/su -F perm=x -F auid>=1000 -F auid!=unset -k privileged-priv_change\n\nThe audit daemon must be restarted for the changes to take effect:\n\n$ sudo augenrules --load",
     A, ["auditd"]),

    ("V-230484", "RHEL-08-030601", "medium",
     "RHEL 8 must enable auditing of processes that start prior to the audit daemon.",
     "Without the capability to generate audit records, it would be difficult to establish, correlate, and investigate the events relating to an incident.",
     "Verify RHEL 8 enables auditing of processes that start prior to the audit daemon with the following commands:\n\n$ sudo grub2-editenv list | grep audit\nkernelopts=root=/dev/mapper/rhel-root ro crashkernel=auto rhgb quiet audit=1\n\nIf \"audit\" is not set to \"1\", is missing, or is commented out, this is a finding.",
     "Configure RHEL 8 to audit processes that start prior to the audit daemon with the following command:\n\n$ sudo grubby --update-kernel=ALL --args=audit=1\n\nAdd the argument to \"/etc/default/grub\" so it persists across kernel updates.",
     A, ["auditd", "boot"]),

    ("V-230486", "RHEL-08-030620", "medium",
     "RHEL 8 audit tools must have a mode of 0755 or less permissive.",
     "Protecting audit information also includes identifying and protecting the tools used to view and manipulate log data.",
     "Verify the audit tools have a mode of \"0755\" or less permissive with the following command:\n\n$ sudo stat -c \"%a %n\" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/rsyslogd /sbin/augenrules\n755 /sbin/auditctl\n\nIf any of the audit tools have a mode more permissive than \"0755\", this is a finding.",
     "Configure the audit tools to have a mode of \"0755\" or less permissive with the following command:\n\n$ sudo chmod 0755 /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/rsyslogd /sbin/augenrules",
     A, ["auditd", "filesystem"]),

    ("V-230492", "RHEL-08-030741", "medium",
     "RHEL 8 must disable the chrony daemon from acting as a server.",
     "Minimizing the exposure of the server functionality of the chrony daemon diminishes the attack surface.",
     "Verify RHEL 8 disables the chrony daemon from acting as a server with the following command:\n\n$ sudo grep -w port /etc/chrony.conf\nport 0\n\nIf the \"port\" option is not set to \"0\", is commented out, or is missing, this is a finding.",
     "Configure RHEL 8 to disable the chrony daemon from acting as a server by adding or modifying the following line in \"/etc/chrony.conf\":\n\nport 0",
     A, ["services"]),

    ("V-230494", "RHEL-08-040000", "high",
     "RHEL 8 must not have the telnet-server package installed.",
     "It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives.",
     "Check to see if the telnet-server package is installed with the following command:\n\n$ sudo yum list installed telnet-server\n\nIf the telnet-server package is installed, this is a finding.",
     "Configure the operating system to disable non-essential capabilities by removing the telnet-server package from the system with the following command:\n\n$ sudo yum remove telnet-server",
     A, ["packages"]),

    ("V-230495", "RHEL-08-040001", "medium",
     "RHEL 8 must not have any automated bug reporting tools installed.",
     "It is detrimental for operating systems to provide, or install by default, functionality exceeding requirements or mission objectives.",
     "Verify the operating system does not have automated bug reporting tools installed with the following command:\n\n$ sudo yum list installed abrt*\n\nIf any automated bug reporting tool packages are installed, this is a finding.",
     "Configure the operating system to disable non-essential capabilities by removing automated bug reporting packages from the system with the following command:\n\n$ sudo yum remove abrt*",
     A, ["packages"]),

    ("V-230502", "RHEL-08-040020", "medium",
     "RHEL 8 must be configured to prevent unrestricted mail relaying.",
     "If unrestricted mail relaying is permitted, unauthorized senders could use this host as a mail relay for the purpose of sending spam or other unauthorized activity.",
     "Verify the system is configured to prevent unrestricted mail relaying with the following command:\n\n$ sudo postconf -n smtpd_client_restrictions\nsmtpd_client_restrictions = permit_mynetworks,reject\n\nIf the \"smtpd_client_restrictions\" parameter contains any entries other than \"permit_mynetworks\" and \"reject\", this is a finding. If the parameter is missing, this is a finding.\n\nIf postfix is not installed, this is Not Applicable.",
     "If \"postfix\" is installed, modify the \"/etc/postfix/main.cf\" file to restrict client connections to the local network with the following command:\n\n$ sudo postconf -e 'smtpd_client_restrictions = permit_mynetworks,reject'",
     A, ["services", "network"]),

    ("V-230507", "RHEL-08-040060", "medium",
     "RHEL 8 must be configured to disable USB mass storage.",
     "USB mass storage permits easy introduction of unknown devices, thereby facilitating malicious activity.",
     "Verify the operating system disables the ability to load the USB Storage kernel module with the following command:\n\n$ sudo grep -ri usb-storage /etc/modprobe.d/ | grep -i \"/bin/false\"\ninstall usb-storage /bin/false\n\nIf the command does not return any output, or the line is commented out, this is a finding.",
     "Configure the operating system to disable the ability to use the USB Storage kernel module.\n\nAdd or update the following lines in the file \"/etc/modprobe.d/blacklist.conf\":\n\ninstall usb-storage /bin/false\nblacklist usb-storage",
     A, ["kernel"]),

    ("V-230511", "RHEL-08-040090", "medium",
     "A RHEL 8 firewall must employ a deny-all, allow-by-exception policy for allowing connections to other systems.",
     "Failure to restrict network connectivity only to authorized systems permits inbound connections from malicious systems.",
     "Verify the firewall is configured to employ a deny-all, allow-by-exception policy for allowing connections to other systems with the following commands:\n\n$ sudo firewall-cmd --state\nrunning\n\n$ sudo firewall-cmd --get-active-zones\npublic\n  interfaces: ens33\n\n$ sudo firewall-cmd --info-zone=public | grep target\n  target: DROP\n\nAsk the System Administrator for the site or program Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA). Verify the services allowed by the firewall match the PPSM CLSA.\n\nIf the firewall is not configured to employ a deny-all, allow-by-exception policy, this is a finding.",
     "Configure the \"firewalld\" daemon to employ a deny-all, allow-by-exception policy.\n\nSet the zone target to DROP and add only the ports and services identified in the PPSM CLSA:\n\n$ sudo firewall-cmd --permanent --zone=public --set-target=DROP\n$ sudo firewall-cmd --reload",
     N, ["firewall", "network"]),

    ("V-230512", "RHEL-08-040100", "medium",
     "A firewall must be installed on RHEL 8.",
     "Remote access services, such as those providing remote access to network devices and information systems, increase risk and expose those systems to possible cyber attacks.",
     "Verify that firewalld is installed with the following command:\n\n$ sudo yum list installed firewalld\nfirewalld.noarch     0.8.2-7.el8      @anaconda\n\nIf the firewalld package is not installed, ask the System Administrator if another firewall is installed. If no firewall is installed, this is a finding.",
     "Install firewalld with the following command:\n\n$ sudo yum install firewalld",
     A, ["firewall", "network"]),

    ("V-230514", "RHEL-08-040110", "medium",
     "RHEL 8 wireless network adapters must be disabled.",
     "Without protection of communications with wireless peripherals, confidentiality and integrity may be compromised.",
     "Verify there are no wireless interfaces configured on the system with the following command:\n\nNote: This requirement is Not Applicable for systems that do not have physical wireless network radios.\n\n$ sudo nmcli device status\n\nIf a wireless interface is configured and its use on the system is not documented with the Information System Security Officer (ISSO) as an operational requirement, this is a finding.",
     "Configure the system to disable all wireless network interfaces with the following command:\n\n$ sudo nmcli radio all off",
     N, ["network"]),

    ("V-230526", "RHEL-08-040209", "medium",
     "RHEL 8 must not accept router advertisements on all IPv6 interfaces by default.",
     "Routing protocol daemons are typically used on routers to exchange network topology information with other routers.",
     "Verify RHEL 8 does not accept router advertisements on all IPv6 interfaces by default, unless the system is a router.\n\nNote: If IPv6 is disabled on the system, this requirement is Not Applicable.\n\nCheck the value of the accept_ra variable with the following command:\n\n$ sudo sysctl net.ipv6.conf.default.accept_ra\nnet.ipv6.conf.default.accept_ra = 0\n\nIf the returned line does not have a value of \"0\", or a line is not returned, this is a finding.",
     "Configure RHEL 8 to not accept router advertisements on all IPv6 interfaces unless the system is a router.\n\nAdd or edit the following line in a system configuration file in the \"/etc/sysctl.d/\" directory:\n\nnet.ipv6.conf.default.accept_ra = 0\n\nLoad settings from all system configuration files with the following command:\n\n$ sudo sysctl --system",
     N, ["network", "kernel"]),

    ("V-230535", "RHEL-08-040286", "medium",
     "RHEL 8 must use reverse path filtering on all IPv4 interfaces.",
     "Enabling reverse path filtering drops packets with source addresses that should not have been able to be received on the interface on which they were received.",
     "Verify RHEL 8 uses reverse path filtering on all IPv4 interfaces with the following commands:\n\n$ sudo sysctl net.ipv4.conf.all.rp_filter\nnet.ipv4.conf.all.rp_filter = 1\n\nIf the returned line does not have a value of \"1\", or a line is not returned, this is a finding.",
     "Configure RHEL 8 to use reverse path filtering on all IPv4 interfaces.\n\nAdd or edit the following line in a system configuration file in the \"/etc/sysctl.d/\" directory:\n\nnet.ipv4.conf.all.rp_filter = 1\n\nLoad settings from all system configuration files with the following command:\n\n$ sudo sysctl --system",
     A, ["network", "kernel"]),

    ("V-230539", "RHEL-08-040170", "medium",
     "The x86 Ctrl-Alt-Delete key sequence must be disabled on RHEL 8.",
     "A locally logged-on user who presses Ctrl-Alt-Delete, when at the console, can reboot the system.",
     "Verify RHEL 8 is not configured to reboot the system when Ctrl-Alt-Delete is pressed with the following command:\n\n$ sudo systemctl status ctrl-alt-del.target\nctrl-alt-del.target\n   Loaded: masked (Reason: Unit ctrl-alt-del.target is masked.)\n   Active: inactive (dead)\n\nIf the ctrl-alt-del.target is not masked, this is a finding.",
     "Configure the system to disable the Ctrl-Alt-Delete sequence for the command line with the following commands:\n\n$ sudo systemctl disable --now ctrl-alt-del.target\n$ sudo systemctl mask --now ctrl-alt-del.target",
     A, ["services"]),

    ("V-230546", "RHEL-08-040180", "medium",
     "The debug-shell systemd service must be disabled on RHEL 8.",
     "The debug-shell requires no authentication and provides root privileges to anyone who has physical access to the machine.",
     "Verify the debug-shell service is disabled with the following command:\n\n$ sudo systemctl status debug-shell.service\ndebug-shell.service\n   Loaded: masked (Reason: Unit debug-shell.service is masked.)\n   Active: inactive (dead)\n\nIf the debug-shell service is not masked and inactive, this is a finding.",
     "Configure the system to mask the debug-shell service with the following commands:\n\n$ sudo systemctl disable --now debug-shell.service\n$ sudo systemctl mask --now debug-shell.service",
     A, ["services"]),

    ("V-230550", "RHEL-08-010800", "high",
     "RHEL 8 must enable the SELinux targeted policy.",
     "Without verification of the security functions, security functions may not operate correctly and the failure may go unnoticed.",
     "Ensure the operating system verifies correct operation of all security functions.\n\nCheck if SELinux is active and is enforcing the targeted policy with the following command:\n\n$ sudo sestatus\nSELinux status:                 enabled\nLoaded policy name:             targeted\nCurrent mode:                   enforcing\n\nIf the \"Loaded policy name\" is not set to \"targeted\", this is a finding.",
     "Configure RHEL 8 to verify correct operation of all security functions.\n\nSet the \"SELinuxtype\" to the \"targeted\" policy by modifying the \"/etc/selinux/config\" file to have the following line:\n\nSELINUXTYPE=targeted\n\nA reboot is required for the changes to take effect.",
     A, ["selinux"]),

    # --- Manual: policy, documentation, physical, or human-judgement checks ---
    ("V-230228", "RHEL-08-010070", "medium",
     "All RHEL 8 remote access methods must be monitored.",
     "Remote access services, such as those providing remote access to network devices and information systems, increase risk and expose those systems to possible cyber attacks.",
     "Verify that RHEL 8 monitors all remote access methods.\n\nAsk the System Administrator to demonstrate how remote access sessions are monitored and logged. Review the documented procedure with the Information System Security Officer (ISSO).\n\nIf there is no documented procedure for monitoring remote access, this is a finding.",
     "Document the procedure for monitoring all remote access methods and obtain ISSO approval. Ensure the procedure is reviewed annually.",
     M, []),

    ("V-230236", "RHEL-08-010150", "medium",
     "The RHEL 8 operating system must implement DoD-approved encryption in the OpenSSL package.",
     "Without cryptographic integrity protections, information can be altered by unauthorized users without detection.",
     "Verify that system-wide crypto policies are in effect and the site has documented its deviations, if any.\n\nThe Information System Security Officer (ISSO) will verify that any deviation from the DoD-approved cryptographic policy is documented, justified, and approved in writing.\n\nIf deviations exist and are not documented and approved, this is a finding.",
     "The ISSO will document and obtain written approval for any deviation from the DoD-approved cryptographic policy, or remove the deviation.",
     M, ["crypto"]),

    ("V-230263", "RHEL-08-010340", "medium",
     "RHEL 8 must be configured so that the cryptographic hashes of system files match vendor values.",
     "Without verification of the security functions, security functions may not operate correctly and the failure may go unnoticed.",
     "Verify the cryptographic hashes of system files match vendor values.\n\nThe System Administrator will review the output of the package verification command with the Information System Security Officer (ISSO) and document any expected deviations, such as locally approved configuration file changes.\n\nIf deviations are present and have not been documented and approved by the ISSO, this is a finding.",
     "The System Administrator will investigate each reported deviation and, with ISSO approval, either restore the vendor file or document the deviation as an accepted local change.",
     M, []),

    ("V-230288", "RHEL-08-010510", "medium",
     "RHEL 8 must have a documented and approved list of authorized software programs.",
     "Utilizing a whitelist provides a configuration management method for allowing the execution of only authorized software.",
     "Verify the site has a documented and ISSO-approved list of software authorized to execute on the system.\n\nAsk the System Administrator for the approved software list. Compare the installed packages against the list.\n\nIf the site does not have an approved software list, this is a finding.",
     "Develop a list of software authorized to execute on the system and obtain Information System Security Officer (ISSO) approval. Review the list annually.",
     M, []),

    ("V-230312", "RHEL-08-010600", "medium",
     "RHEL 8 must be maintained in a documented baseline configuration.",
     "Configuration management is the process of controlling changes to a system throughout its lifecycle.",
     "Verify the system is maintained in a documented baseline configuration.\n\nThe Information System Security Officer (ISSO) will verify that a baseline configuration document exists, is current, and that changes to the system are processed through the organization's configuration control board.\n\nIf no current baseline configuration document exists, this is a finding.",
     "Document the system baseline configuration and submit it to the configuration control board for approval. Review and update the baseline whenever an approved change is implemented.",
     M, []),

    ("V-230324", "RHEL-08-010680", "low",
     "RHEL 8 must be located in a controlled access area.",
     "Physical access controls are a prerequisite to every logical control the operating system implements.",
     "Verify the system is located in a controlled access area.\n\nInspect the physical location of the system. The Information System Security Officer (ISSO) will confirm the area meets the physical security requirements for the system's classification level.\n\nIf the system is not located in a controlled access area, this is a finding.",
     "Relocate the system to a controlled access area meeting the physical security requirements for its classification level, or obtain a documented risk acceptance from the Authorizing Official.",
     M, []),

    ("V-230341", "RHEL-08-020020", "medium",
     "RHEL 8 users must be trained on the acceptable use policy before being granted access.",
     "Organizations are required to ensure users are aware of their responsibilities before granting access.",
     "Verify all users with accounts on the system have completed acceptable use training.\n\nAsk the System Administrator for training records. The Information System Security Officer (ISSO) will verify records exist for every interactive account on the system.\n\nIf training records are missing for any account, this is a finding.",
     "Ensure every user completes acceptable use training before an account is created, and retain the training records for the life of the account.",
     M, []),

    ("V-230392", "RHEL-08-030040", "medium",
     "RHEL 8 must take appropriate action when an audit processing failure occurs and notify designated personnel.",
     "It is critical for the appropriate personnel to be aware if a system is at risk of failing to process audit logs as required.",
     "Verify that designated personnel are notified when an audit processing failure occurs.\n\nAsk the System Administrator to identify the designated personnel and demonstrate how they are notified. Review the notification procedure with the Information System Security Officer (ISSO).\n\nIf there is no documented notification procedure, or the designated personnel are not identified, this is a finding.",
     "Document the audit processing failure notification procedure, identify the designated personnel by role, and obtain ISSO approval.",
     M, ["auditd"]),

    ("V-230498", "RHEL-08-040004", "medium",
     "RHEL 8 must have an approved contingency plan for restoring the system after a failure.",
     "Without a contingency plan, restoration of the system after a failure is unlikely to meet the organization's recovery time objective.",
     "Verify an approved contingency plan exists for the system.\n\nThe Information System Security Officer (ISSO) will verify the plan is current, has been tested within the last year, and that the test results are documented.\n\nIf no current, tested contingency plan exists, this is a finding.",
     "Develop a contingency plan for the system, test it annually, document the results, and obtain ISSO approval.",
     M, []),

    # --- Needs-review: automatable in principle, but the value is site-defined ---
    ("V-230331", "RHEL-08-020009", "medium",
     "RHEL 8 must automatically lock an account until the locked account is released by an administrator when three unsuccessful logon attempts occur during a 15-minute time period.",
     "By limiting the number of failed logon attempts, the risk of unauthorized system access via user password guessing is reduced.",
     "Note: If the system administrator (SA) demonstrates the use of an approved centralized account management method that locks an account after three unsuccessful logon attempts within a period of 15 minutes, this requirement is Not Applicable.\n\nCheck that the system locks an account after three unsuccessful logon attempts within a period of 15 minutes with the following commands:\n\n$ sudo grep 'unlock_time =' /etc/security/faillock.conf\nunlock_time = 0\n\nIf the \"unlock_time\" option is not set to \"0\", is missing or commented out, this is a finding.",
     "Configure the operating system to lock an account until released by an administrator when three unsuccessful logon attempts occur in 15 minutes.\n\nAdd/Modify the \"/etc/security/faillock.conf\" file to match the following line:\n\nunlock_time = 0\n\nNote: If a centralized account management method is in use, apply the equivalent setting there instead; the local file will not be authoritative.",
     N, ["pam", "authentication"]),

    ("V-230378", "RHEL-08-020280", "medium",
     "All RHEL 8 local interactive user accounts must be assigned a home directory upon creation.",
     "If local interactive users are not assigned a valid home directory, there is no place for the storage and control of files they should own.",
     "Verify all local interactive users on RHEL 8 are assigned a home directory upon creation with the following command:\n\n$ sudo grep -i create_home /etc/login.defs\nCREATE_HOME yes\n\nIf the value for \"CREATE_HOME\" parameter is not set to \"yes\", the line is missing, or the line is commented out, this is a finding.\n\nNote: If the site uses a directory service that provisions home directories on a fileserver, determine with the System Administrator whether CREATE_HOME is the correct control point for this system.",
     "Configure RHEL 8 to assign home directories to all new local interactive users by setting the \"CREATE_HOME\" parameter in \"/etc/login.defs\" to \"yes\":\n\nCREATE_HOME yes\n\nIf home directories are provisioned by a directory service, configure the equivalent setting there instead.",
     N, ["authentication"]),

    ("V-230399", "RHEL-08-030070", "medium",
     "RHEL 8 audit logs must have a mode of 0600 or less permissive to prevent unauthorized read access.",
     "Unauthorized disclosure of audit records can reveal system and configuration data to attackers.",
     "Verify the audit logs have a mode of \"0600\" or less permissive.\n\nFirst determine where the audit logs are stored with the following command:\n\n$ sudo grep -iw log_file /etc/audit/auditd.conf\nlog_file = /var/log/audit/audit.log\n\nUsing the location of the audit log file, check if each audit log has a mode of \"0600\" or less permissive with the following command, substituting the correct audit log path:\n\n$ sudo stat -c \"%a %n\" /var/log/audit/*\n600 /var/log/audit/audit.log\n\nIf the audit logs have a mode more permissive than \"0600\", this is a finding.",
     "Configure the audit logs to be protected from unauthorized read access by setting the correct permissive mode with the following command, substituting the audit log path from \"auditd.conf\":\n\n$ sudo chmod 0600 /var/log/audit/*",
     A, ["auditd", "filesystem"]),

    ("V-230505", "RHEL-08-040023", "medium",
     "The RHEL 8 file system automounter must be disabled unless required.",
     "Automatically mounting file systems permits easy introduction of unknown devices, thereby facilitating malicious activity.",
     "Verify the operating system disables the ability to automount devices.\n\nNote: If the autofs service is required for the system's documented mission, and its use is approved by the Information System Security Officer (ISSO), this requirement is Not Applicable.\n\nCheck that the autofs service is disabled with the following command:\n\n$ sudo systemctl is-enabled autofs\ndisabled\n\nIf the autofs service is enabled and is not documented as an operational requirement, this is a finding.",
     "Configure the operating system to disable the ability to automount devices.\n\nIf autofs is not required for the mission:\n\n$ sudo systemctl mask --now autofs\n\nIf autofs is required, document the requirement and obtain ISSO approval instead of disabling it.",
     N, ["services"]),

    ("V-230532", "RHEL-08-040259", "medium",
     "RHEL 8 must not enable IPv6 packet forwarding unless the system is a router.",
     "Routing protocol daemons are typically used on routers to exchange network topology information with other routers.",
     "Verify RHEL 8 is not performing IPv6 packet forwarding, unless the system is a router.\n\nNote: If IPv6 is disabled on the system, this requirement is Not Applicable.\n\nCheck that IPv6 forwarding is disabled with the following command:\n\n$ sudo sysctl net.ipv6.conf.all.forwarding\nnet.ipv6.conf.all.forwarding = 0\n\nIf the returned line does not have a value of \"0\", or a line is not returned, and the system is not a router, this is a finding.",
     "Configure RHEL 8 to not allow IPv6 packet forwarding, unless the system is a router.\n\nAdd or edit the following line in a system configuration file in the \"/etc/sysctl.d/\" directory:\n\nnet.ipv6.conf.all.forwarding = 0\n\nLoad settings from all system configuration files with the following command:\n\n$ sudo sysctl --system\n\nIf the system is a router, this requirement is Not Applicable and the setting must not be changed.",
     N, ["network", "kernel"]),
]
